test: AWS lambda 32

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -49,37 +49,37 @@ jobs:
       - name: Install dependencies
         run: npm install
 
-      - name: Unit tests
-        run: npm run test
+      # - name: Unit tests
+      #   run: npm run test
 
-      - name: Clean up Docker containers
-        run: docker-compose down -v || true
+      # - name: Clean up Docker containers
+      #   run: docker-compose down -v || true
 
-      - name: Build Docker images
-        run: docker-compose build
+      # - name: Build Docker images
+      #   run: docker-compose build
 
-      - name: Start Docker Compose services
-        run: docker-compose up -d
-        env:
-          DATABASE_URL: postgresql://postgres:docker@localhost:5433/hub-postgres-db  # Match the port mapping
+      # - name: Start Docker Compose services
+      #   run: docker-compose up -d
+      #   env:
+      #     DATABASE_URL: postgresql://postgres:docker@localhost:5433/hub-postgres-db  # Match the port mapping
 
-      - name: Wait for Postgres to be ready
-        run: |
-          until docker-compose exec -T postgres pg_isready -U postgres -d hub-postgres-db; do
-            echo "Waiting for postgres..."
-            sleep 1
-          done
+      # - name: Wait for Postgres to be ready
+      #   run: |
+      #     until docker-compose exec -T postgres pg_isready -U postgres -d hub-postgres-db; do
+      #       echo "Waiting for postgres..."
+      #       sleep 1
+      #     done
 
-      - name: Run Prisma migrations
-        run: npx prisma migrate deploy
-        env:
-          DATABASE_URL: postgresql://postgres:docker@localhost:5433/hub-postgres-db  # Match the port mapping
+      # - name: Run Prisma migrations
+      #   run: npx prisma migrate deploy
+      #   env:
+      #     DATABASE_URL: postgresql://postgres:docker@localhost:5433/hub-postgres-db  # Match the port mapping
 
-      - name: Change permissions
-        run: sudo chmod -R 777 ./data/pg
+      # - name: Change permissions
+      #   run: sudo chmod -R 777 ./data/pg
 
-      - name: Run tests
-        run: npm run test:e2e
+      # - name: Run tests
+      #   run: npm run test:e2e
       
       - name: Build NestJS
         run: npm run build
@@ -90,8 +90,9 @@ jobs:
       - name: Upload to AWS Lambda
         run: |
           aws lambda update-function-code \
-          --function-name MyLambdaFunction \
-          --zip-file fileb://deploy.zip
+            --function-name MyLambdaFunction \
+            --zip-file fileb://deploy.zip
+
 
       # - name: Stop Docker Compose services
       #   if: always()
